import { describe, test, expect, beforeAll } from "vitest";
import { ConvexHttpClient } from "convex/browser";
import { createTestClient, createAuthenticatedClient } from "../../clients/convex-client";
import { getAuthToken } from "../../clients/auth";
import { loadSeedContext } from "../../helpers/load-context";
import { expectToThrow } from "../../helpers/assertions";
import { api } from "../../../convex/_generated/api";
import type { SeedContext } from "../../seed/types";
import type { Id } from "../../../convex/_generated/dataModel";

/**
 * [FR-CS] Audit Logging
 *
 * Tests the platform audit log:
 * - List audit log entries (authenticated)
 * - Filter by actorId
 * - Limit parameter
 * - Auth enforcement (unauthenticated rejected)
 *
 * Note: The `create` mutation is internal-only (called by server functions),
 * so we test the read-side only. Audit entries are generated by other
 * mutations as side effects.
 */
describe("[FR-CS] Audit Logging", () => {
  let ctx: SeedContext;
  let unauthenticatedClient: ConvexHttpClient;

  beforeAll(() => {
    ctx = loadSeedContext();
    unauthenticatedClient = createTestClient();
  });

  async function clientFor(userKey: string) {
    const token = await getAuthToken(ctx.users[userKey].email!);
    return createAuthenticatedClient(token);
  }

  // --------------------------------------------------------------------------
  // Auth enforcement
  // --------------------------------------------------------------------------

  test("unauthenticated user cannot list audit logs", async () => {
    await expectToThrow(
      () => unauthenticatedClient.query(api.platformAuditLog.list, {}),
      "Not authenticated"
    );
  });

  // --------------------------------------------------------------------------
  // Read happy path
  // --------------------------------------------------------------------------

  test("authenticated user can list audit log entries", async () => {
    const client = await clientFor("alice");

    const entries = await client.query(api.platformAuditLog.list, {});

    // Audit log may be empty or populated — verify shape
    expect(Array.isArray(entries)).toBe(true);

    if (entries.length > 0) {
      const entry = entries[0];
      expect(entry.actorId).toBeDefined();
      expect(entry.action).toBeDefined();
      expect(entry.targetEntity).toBeDefined();
      expect(entry.timestamp).toBeDefined();
      expect(typeof entry.timestamp).toBe("number");
    }
  });

  test("audit log respects limit parameter", async () => {
    const client = await clientFor("alice");

    const entries = await client.query(api.platformAuditLog.list, {
      limit: 5,
    });

    expect(entries.length).toBeLessThanOrEqual(5);
  });

  test("audit log can filter by actorId", async () => {
    const client = await clientFor("alice");

    const entries = await client.query(api.platformAuditLog.list, {
      actorId: ctx.users.alice.id as Id<"users">,
    });

    // All returned entries should be for the specified actor
    for (const entry of entries) {
      expect(entry.actorId).toBe(ctx.users.alice.id);
    }
  });

  test("audit log returns entries in descending order (newest first)", async () => {
    const client = await clientFor("alice");

    const entries = await client.query(api.platformAuditLog.list, {
      limit: 10,
    });

    if (entries.length >= 2) {
      for (let i = 0; i < entries.length - 1; i++) {
        expect(entries[i].timestamp).toBeGreaterThanOrEqual(entries[i + 1].timestamp);
      }
    }
  });

  test("default limit is 50 (entries up to 50 returned)", async () => {
    const client = await clientFor("alice");

    const entries = await client.query(api.platformAuditLog.list, {});

    expect(entries.length).toBeLessThanOrEqual(50);
  });

  // --------------------------------------------------------------------------
  // Different users can read audit logs
  // --------------------------------------------------------------------------

  test("any authenticated user can read audit logs", async () => {
    const daveClient = await clientFor("dave");

    const entries = await daveClient.query(api.platformAuditLog.list, {});

    // Dave (athlete) should be able to read audit logs
    expect(Array.isArray(entries)).toBe(true);
  });

  test("coach can read audit logs", async () => {
    const bobClient = await clientFor("bob");

    const entries = await bobClient.query(api.platformAuditLog.list, {});
    expect(Array.isArray(entries)).toBe(true);
  });
});
