/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedModerationRouteImport } from './routes/_authenticated/moderation'
import { Route as AuthenticatedFeatureFlagsRouteImport } from './routes/_authenticated/feature-flags'
import { Route as AuthenticatedExercisesRouteImport } from './routes/_authenticated/exercises'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBenchmarksRouteImport } from './routes/_authenticated/benchmarks'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedTenantsIndexRouteImport } from './routes/_authenticated/tenants/index'
import { Route as AuthenticatedSecurityIndexRouteImport } from './routes/_authenticated/security/index'
import { Route as AuthenticatedIntegrationsIndexRouteImport } from './routes/_authenticated/integrations/index'
import { Route as AuthenticatedComplianceIndexRouteImport } from './routes/_authenticated/compliance/index'
import { Route as AuthenticatedTenantsProvisionRouteImport } from './routes/_authenticated/tenants/provision'
import { Route as AuthenticatedTenantsTenantIdRouteImport } from './routes/_authenticated/tenants/$tenantId'
import { Route as AuthenticatedSecurityApiKeysRouteImport } from './routes/_authenticated/security/api-keys'
import { Route as AuthenticatedComplianceLegalDocumentsRouteImport } from './routes/_authenticated/compliance/legal-documents'
import { Route as AuthenticatedComplianceAgeVerificationRouteImport } from './routes/_authenticated/compliance/age-verification'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedModerationRoute = AuthenticatedModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeatureFlagsRoute =
  AuthenticatedFeatureFlagsRouteImport.update({
    id: '/feature-flags',
    path: '/feature-flags',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExercisesRoute = AuthenticatedExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBenchmarksRoute = AuthenticatedBenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsIndexRoute =
  AuthenticatedTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSecurityIndexRoute =
  AuthenticatedSecurityIndexRouteImport.update({
    id: '/security/',
    path: '/security/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsIndexRoute =
  AuthenticatedIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplianceIndexRoute =
  AuthenticatedComplianceIndexRouteImport.update({
    id: '/compliance/',
    path: '/compliance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsProvisionRoute =
  AuthenticatedTenantsProvisionRouteImport.update({
    id: '/tenants/provision',
    path: '/tenants/provision',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsTenantIdRoute =
  AuthenticatedTenantsTenantIdRouteImport.update({
    id: '/tenants/$tenantId',
    path: '/tenants/$tenantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSecurityApiKeysRoute =
  AuthenticatedSecurityApiKeysRouteImport.update({
    id: '/security/api-keys',
    path: '/security/api-keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplianceLegalDocumentsRoute =
  AuthenticatedComplianceLegalDocumentsRouteImport.update({
    id: '/compliance/legal-documents',
    path: '/compliance/legal-documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComplianceAgeVerificationRoute =
  AuthenticatedComplianceAgeVerificationRouteImport.update({
    id: '/compliance/age-verification',
    path: '/compliance/age-verification',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/benchmarks': typeof AuthenticatedBenchmarksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercises': typeof AuthenticatedExercisesRoute
  '/feature-flags': typeof AuthenticatedFeatureFlagsRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/compliance/age-verification': typeof AuthenticatedComplianceAgeVerificationRoute
  '/compliance/legal-documents': typeof AuthenticatedComplianceLegalDocumentsRoute
  '/security/api-keys': typeof AuthenticatedSecurityApiKeysRoute
  '/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRoute
  '/tenants/provision': typeof AuthenticatedTenantsProvisionRoute
  '/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/security/': typeof AuthenticatedSecurityIndexRoute
  '/tenants/': typeof AuthenticatedTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/benchmarks': typeof AuthenticatedBenchmarksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercises': typeof AuthenticatedExercisesRoute
  '/feature-flags': typeof AuthenticatedFeatureFlagsRoute
  '/moderation': typeof AuthenticatedModerationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/compliance/age-verification': typeof AuthenticatedComplianceAgeVerificationRoute
  '/compliance/legal-documents': typeof AuthenticatedComplianceLegalDocumentsRoute
  '/security/api-keys': typeof AuthenticatedSecurityApiKeysRoute
  '/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRoute
  '/tenants/provision': typeof AuthenticatedTenantsProvisionRoute
  '/compliance': typeof AuthenticatedComplianceIndexRoute
  '/integrations': typeof AuthenticatedIntegrationsIndexRoute
  '/security': typeof AuthenticatedSecurityIndexRoute
  '/tenants': typeof AuthenticatedTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/benchmarks': typeof AuthenticatedBenchmarksRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exercises': typeof AuthenticatedExercisesRoute
  '/_authenticated/feature-flags': typeof AuthenticatedFeatureFlagsRoute
  '/_authenticated/moderation': typeof AuthenticatedModerationRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/compliance/age-verification': typeof AuthenticatedComplianceAgeVerificationRoute
  '/_authenticated/compliance/legal-documents': typeof AuthenticatedComplianceLegalDocumentsRoute
  '/_authenticated/security/api-keys': typeof AuthenticatedSecurityApiKeysRoute
  '/_authenticated/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRoute
  '/_authenticated/tenants/provision': typeof AuthenticatedTenantsProvisionRoute
  '/_authenticated/compliance/': typeof AuthenticatedComplianceIndexRoute
  '/_authenticated/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/_authenticated/security/': typeof AuthenticatedSecurityIndexRoute
  '/_authenticated/tenants/': typeof AuthenticatedTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/announcements'
    | '/audit-log'
    | '/benchmarks'
    | '/dashboard'
    | '/exercises'
    | '/feature-flags'
    | '/moderation'
    | '/settings'
    | '/compliance/age-verification'
    | '/compliance/legal-documents'
    | '/security/api-keys'
    | '/tenants/$tenantId'
    | '/tenants/provision'
    | '/compliance/'
    | '/integrations/'
    | '/security/'
    | '/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/announcements'
    | '/audit-log'
    | '/benchmarks'
    | '/dashboard'
    | '/exercises'
    | '/feature-flags'
    | '/moderation'
    | '/settings'
    | '/compliance/age-verification'
    | '/compliance/legal-documents'
    | '/security/api-keys'
    | '/tenants/$tenantId'
    | '/tenants/provision'
    | '/compliance'
    | '/integrations'
    | '/security'
    | '/tenants'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/announcements'
    | '/_authenticated/audit-log'
    | '/_authenticated/benchmarks'
    | '/_authenticated/dashboard'
    | '/_authenticated/exercises'
    | '/_authenticated/feature-flags'
    | '/_authenticated/moderation'
    | '/_authenticated/settings'
    | '/_authenticated/compliance/age-verification'
    | '/_authenticated/compliance/legal-documents'
    | '/_authenticated/security/api-keys'
    | '/_authenticated/tenants/$tenantId'
    | '/_authenticated/tenants/provision'
    | '/_authenticated/compliance/'
    | '/_authenticated/integrations/'
    | '/_authenticated/security/'
    | '/_authenticated/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feature-flags': {
      id: '/_authenticated/feature-flags'
      path: '/feature-flags'
      fullPath: '/feature-flags'
      preLoaderRoute: typeof AuthenticatedFeatureFlagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exercises': {
      id: '/_authenticated/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AuthenticatedExercisesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/benchmarks': {
      id: '/_authenticated/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof AuthenticatedBenchmarksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/': {
      id: '/_authenticated/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AuthenticatedTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security/': {
      id: '/_authenticated/security/'
      path: '/security'
      fullPath: '/security/'
      preLoaderRoute: typeof AuthenticatedSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/': {
      id: '/_authenticated/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AuthenticatedIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance/': {
      id: '/_authenticated/compliance/'
      path: '/compliance'
      fullPath: '/compliance/'
      preLoaderRoute: typeof AuthenticatedComplianceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/provision': {
      id: '/_authenticated/tenants/provision'
      path: '/tenants/provision'
      fullPath: '/tenants/provision'
      preLoaderRoute: typeof AuthenticatedTenantsProvisionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/$tenantId': {
      id: '/_authenticated/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security/api-keys': {
      id: '/_authenticated/security/api-keys'
      path: '/security/api-keys'
      fullPath: '/security/api-keys'
      preLoaderRoute: typeof AuthenticatedSecurityApiKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance/legal-documents': {
      id: '/_authenticated/compliance/legal-documents'
      path: '/compliance/legal-documents'
      fullPath: '/compliance/legal-documents'
      preLoaderRoute: typeof AuthenticatedComplianceLegalDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance/age-verification': {
      id: '/_authenticated/compliance/age-verification'
      path: '/compliance/age-verification'
      fullPath: '/compliance/age-verification'
      preLoaderRoute: typeof AuthenticatedComplianceAgeVerificationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedBenchmarksRoute: typeof AuthenticatedBenchmarksRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExercisesRoute: typeof AuthenticatedExercisesRoute
  AuthenticatedFeatureFlagsRoute: typeof AuthenticatedFeatureFlagsRoute
  AuthenticatedModerationRoute: typeof AuthenticatedModerationRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedComplianceAgeVerificationRoute: typeof AuthenticatedComplianceAgeVerificationRoute
  AuthenticatedComplianceLegalDocumentsRoute: typeof AuthenticatedComplianceLegalDocumentsRoute
  AuthenticatedSecurityApiKeysRoute: typeof AuthenticatedSecurityApiKeysRoute
  AuthenticatedTenantsTenantIdRoute: typeof AuthenticatedTenantsTenantIdRoute
  AuthenticatedTenantsProvisionRoute: typeof AuthenticatedTenantsProvisionRoute
  AuthenticatedComplianceIndexRoute: typeof AuthenticatedComplianceIndexRoute
  AuthenticatedIntegrationsIndexRoute: typeof AuthenticatedIntegrationsIndexRoute
  AuthenticatedSecurityIndexRoute: typeof AuthenticatedSecurityIndexRoute
  AuthenticatedTenantsIndexRoute: typeof AuthenticatedTenantsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedBenchmarksRoute: AuthenticatedBenchmarksRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExercisesRoute: AuthenticatedExercisesRoute,
  AuthenticatedFeatureFlagsRoute: AuthenticatedFeatureFlagsRoute,
  AuthenticatedModerationRoute: AuthenticatedModerationRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedComplianceAgeVerificationRoute:
    AuthenticatedComplianceAgeVerificationRoute,
  AuthenticatedComplianceLegalDocumentsRoute:
    AuthenticatedComplianceLegalDocumentsRoute,
  AuthenticatedSecurityApiKeysRoute: AuthenticatedSecurityApiKeysRoute,
  AuthenticatedTenantsTenantIdRoute: AuthenticatedTenantsTenantIdRoute,
  AuthenticatedTenantsProvisionRoute: AuthenticatedTenantsProvisionRoute,
  AuthenticatedComplianceIndexRoute: AuthenticatedComplianceIndexRoute,
  AuthenticatedIntegrationsIndexRoute: AuthenticatedIntegrationsIndexRoute,
  AuthenticatedSecurityIndexRoute: AuthenticatedSecurityIndexRoute,
  AuthenticatedTenantsIndexRoute: AuthenticatedTenantsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
